<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Media / Upload Configuration
|--------------------------------------------------------------------------
|
| Centralised limits and storage settings for user-uploaded media (post
| images/videos, reels, avatars, chat attachments). Values are reused by
| validation rules and the FFmpeg transcoding jobs.
|
*/

return [
    'disk' => env('MEDIA_DISK', env('FILESYSTEM_DISK', 'public')),

    'image' => [
        'max_kb'     => (int) env('MEDIA_IMAGE_MAX_KB', 8192),     // 8 MB
        'mimes'      => ['jpg', 'jpeg', 'png', 'webp', 'gif'],
        'max_width'  => 1920,
        'thumb_width' => 480,
    ],

    'video' => [
        'max_kb' => (int) env('MEDIA_VIDEO_MAX_KB', 204800),       // 200 MB
        'mimes'  => ['mp4', 'mov', 'avi', 'mkv', 'webm'],
        // HLS ladder generated by FFmpeg for adaptive streaming.
        'hls_renditions' => [
            ['name' => '360p',  'width' => 640,  'height' => 360,  'bitrate' => 800],
            ['name' => '720p',  'width' => 1280, 'height' => 720,  'bitrate' => 2500],
            ['name' => '1080p', 'width' => 1920, 'height' => 1080, 'bitrate' => 5000],
        ],
    ],

    'reel' => [
        'max_seconds' => (int) env('MEDIA_REEL_MAX_SECONDS', 90),
        'max_kb'      => (int) env('MEDIA_REEL_MAX_KB', 102400),   // 100 MB
    ],
];
